[workspace]
members = [
    "derive",
    "tests",

    "json",
    "json/benches",
]

[package]
name = "sval"
version = "0.0.0"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]
edition = "2018"

[features]
std = []
derive = ["sval_derive"]
test = ["std"]

# Default `serde` support requires `std`
# because `serde::ser::Error` needs extra
# trait bounds when compiled with the `std`
# feature, which is the default for `serde`.
serde = ["std", "serde_lib/std"]

[dependencies.serde_lib]
version = "1"
optional = true
default-features = false
package = "serde"

[dependencies.sval_derive]
path = "./derive"
optional = true
