[package]
name = "val_serde"
version = "0.1.0"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]
edition = "2018"

[features]
default = ["std"]
std = ["val/std", "serde/std"]

[dependencies.val]
path = "../val"

[dependencies.serde]
version = "~1"
default-features = false
