[package]
name = "sval"
version = "0.0.0"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]
edition = "2018"
publish = false

[features]
std = []

[dependencies.serde]
version = "1"
optional = true
default-features = false
