[package]
name = "serde_value"
version = "0.0.0"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]
edition = "2018"
publish = false

[dependencies.serde]
version = "~1"
default-features = false

[dependencies.serde_derive]
version = "~1"
