[package]
name = "val_visit"
version = "0.0.0"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]
edition = "2018"
publish = false

[dependencies.val]
path = "../../val"

[dependencies.val_value]
path = "../val_value"
